### PR TITLE
Add pull quote variants

### PR DESCRIPTION
**Pull request by andyngo**
Reference issue: https://github.com/hypered/design-system/issues/28

This PR adds one (or more) Pull Quote examples. Right now this is what it looks like:
Screenshot 2019-12-18 at 12 32 52

Would you like to see a few more variants here? @noteed 

Edit: I'll only regenerate the docs when the PR is good to go. :)

### CODE REVIEW

**Comment by noteed** [comment]
Maybe just make the big quotes optional ?

You don't even need to re-generate the docs, I can do it once in a while. (I'll try to change the way it works and use a different gh-pages branch, instead of using the master branch, it's annoying to see those commits.)

**Comment by andyngo** [comment]
I can make it optional, but it'll be difficult to capture the 'pull quote' look. I'll see what I can do. :)

**Comment by noteed** [comment]
Thanks ! I now realize that maybe you hadn't finished yet...

**Comment by andyngo** [comment]
Hahaha, yes. I was wondering why my Git push was not working, I'll cherry pick the commits and create another PR for the updated Pull Quotes.

**Pull request merged**
