### PR TITLE
Add css modal

### PR DESCRIPTION
**Pull request by andyngo**
Add HTML/CSS-only modal. This uses the `<input type="checkbox` />` trick to toggle the Modal.

Modal with text content:
Screenshot 2020-04-22 at 14 58 50

Modal with form/login:
Screenshot 2020-04-22 at 14 59 05

### CODE REVIEW

**Comment by noteed** [comment]
Thanksm this is really cool.

Just one thing: we have a Storybook entry for a login form. Can you add this sign in form there and re-use that component in this story ? ( I guess this should be Sign up, otherwise Login and Sign in is redundant.)

**Comment by andyngo** [comment]
Sure, let me get to that. Will push some changes when it's done.

**Comment by noteed** [comment]
Btw, is it the same trick that could be used for a mobile menu ?

**Comment by andyngo** [comment]
@noteed You're right, I think it's similar—we can make a mobile menu with the same technique. Let's do that?

**Comment by noteed** [comment]
Sure!

**Pull request merged**
