### PR TITLE
Add whitespace examples

### PR DESCRIPTION
**Pull request by andyngo**
This PR addresses the following issue: https://github.com/hypered/design-system/issues/26

- Added examples of how to handle whitespace when using ``
localhost_6006_iframe html_id=images--examples

- Added examples of how to handle whitespace when using `<div>`
Screenshot 2019-12-24 at 16 31 19

### CODE REVIEW

**Comment by andyngo** [comment]
Styled the whitespace examples as per email like so:
localhost_6006_iframe html_id=whitespace--examples (2)

**Comment by noteed** [comment]
:grin: I really like this PR. I wish I could merge it tonight :christmas_tree: 

Please keep the colors of the div cards as-is, they-re great ! I noticed that the vertical line on the right is colored; this is not the case on the other PR. Maybe you should adapt the other PR ?

About the `placeholder.svg` file, I expected it to be copied to `storybook-static/` when running `yarn run build-storybook` but this is not the case. Is it normal ?

**Comment by andyngo** [comment]
I've included the static folder path when executing `yarn run build-storybook`. This should copy all the files in static into `storybook-static/`, though we'll have to see if it works when deployed to GH pages. If it does not, I might need to do one of the following:

1. Import static files where it's used for example:
```
import placeholderImage from '../../static/img/placeholder.svg'

export const Image = () => (
  <img src={placeholderImage} />
)
```
or
2. Mess around with the `process.env.BACKEND_URL` flag as we did previously for the next.js static site.

---

I've also updated the examples in #42 to inherit the primary text-colour instead of setting it manually.

😄

**Comment by noteed** [comment]
That seems good locally. I will merge it.

**Pull request merged**
